################################################################################
#   Copyright (c) 2019 AT&T Intellectual Property.                             #
#   Copyright (c) 2019 Nokia.                                                  #
#                                                                              #
#   Licensed under the Apache License, Version 2.0 (the "License");            #
#   you may not use this file except in compliance with the License.           #
#   You may obtain a copy of the License at                                    #
#                                                                              #
#       http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                              #
#   Unless required by applicable law or agreed to in writing, software        #
#   distributed under the License is distributed on an "AS IS" BASIS,          #
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
#   See the License for the specific language governing permissions and        #
#   limitations under the License.                                             #
################################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.deploymentname.appmgr" . }}
  namespace: {{ include "common.namespace.platform" . }}
  labels:
    app: {{ include "common.namespace.platform" . }}-{{ include "common.name.appmgr" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.appmgr.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "common.namespace.platform" . }}-{{ include "common.name.appmgr" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      {{- if .Values.appmgr.annotations }}
      annotations:
        {{- .Values.appmgr.annotations | nindent 8 -}}
      {{ end }}
      labels:
        app: {{ include "common.namespace.platform" . }}-{{ include "common.name.appmgr" . }}
        release: {{ .Release.Name }}
    spec:
      hostname: {{ include "common.name.appmgr" . }}
      serviceAccountName: {{ include "common.serviceaccountname.appmgr" . }}
      imagePullSecrets:
        - name: {{ include "common.repositoryCred" . }}
      containers:
        - name: {{ include "common.containername.appmgr" . }}
          image: {{ include "common.repository" . }}/{{ .Values.appmgr.image.name }}:{{ .Values.appmgr.image.tag }}
          imagePullPolicy: {{ include "common.pullPolicy" . }}
          ports:
            - name: http
              containerPort: {{ include "common.serviceport.appmgr.http" . }}
              protocol: TCP
            - name: rmrroute
              containerPort: {{ include "common.serviceport.appmgr.rmr.route" . }}
              protocol: TCP
            - name: rmrdata
              containerPort: {{ include "common.serviceport.appmgr.rmr.data" . }}
              protocol: TCP
          volumeMounts:
            - name: config-volume
              mountPath: {{ .Values.appmgr.appconfigpath }}/appmgr.yaml
              subPath: appmgr.yaml
            - name: secret-volume
              mountPath: {{ .Values.appmgr.appsecretpath }}
            - name: cert-volume
              mountPath: {{ .Values.appmgr.appcertpath }}
          envFrom:
            - configMapRef:
                name: {{ include "common.configmapname.appmgr" . }}-env
          livenessProbe:
            #exec:
            #  command:
            #    - /bin/bash
            #    - -c
            #    - ps -ef | grep {{ .Values.livenessprocessname }}| grep -v "grep"
            #initialDelaySeconds: 120
            #periodSeconds: 30
          readinessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          restartPolicy: Always
          securityContext:
            # ubuntu
            #runAsUser: 1000
            #allowPrivilegeEscalation: false
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "common.configmapname.appmgr" . }}-appconfig
        - name: secret-volume
          secret:
            secretName: {{ include "common.helmrepositorycred" . }}
        - name: cert-volume
          configMap:
            name: {{ include "common.helmrepositorycert" . }}
