apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "common.ingressname.appmgr" . }}
spec:
  rules:
  - http:
      paths:
      - path: {{ include ""common.kongpath.ric.appmgr" . }}
        backend:
          serviceName: {{ include "common.servicename.appmgr.http" . }}
          servicePort: {{ include "common.serviceport.appmgr.http" . }}
