---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "common.serviceaccountname.appmgr" . }}
  namespace: {{ include "common.namespace.platform" . }}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: {{ include "common.serviceaccountname.appmgr" . }}-{{ include "common.helmrepositorytillernamespace" . }}-access
  namespace: {{ include "common.helmrepositorytillernamespace" . }}
rules:
- apiGroups: [""]
  resources: ["pods", "pods/portforward"]
  verbs: ["get", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: {{ include "common.serviceaccountname.appmgr" . }}-{{ include "common.helmrepositorytillernamespace" .}}-access
  namespace: {{ include "common.helmrepositorytillernamespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "common.serviceaccountname.appmgr" . }}-{{ include "common.helmrepositorytillernamespace" .}}-access
subjects:
  - kind: ServiceAccount
    name: {{ include "common.serviceaccountname.appmgr" . }}
    namespace: {{ include "common.namespace.platform" . }}
