################################################################################
#   Copyright (c) 2019 AT&T Intellectual Property.                             #
#   Copyright (c) 2019 Nokia.                                                  #
#                                                                              #
#   Licensed under the Apache License, Version 2.0 (the "License");            #
#   you may not use this file except in compliance with the License.           #
#   You may obtain a copy of the License at                                    #
#                                                                              #
#       http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                              #
#   Unless required by applicable law or agreed to in writing, software        #
#   distributed under the License is distributed on an "AS IS" BASIS,          #
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
#   See the License for the specific language governing permissions and        #
#   limitations under the License.                                             #
################################################################################

repository: "nexus3.o-ran-sc.org:10004"
#repositoryOverride: "nexus3.o-ran-sc.org:10004"
imagePullPolicy: IfNotPresent
repositoryCred: docker-reg-cred

# Helm Repo for xApp
# By default a local helm repo is used. The global setting will override
# the default value. You can further override using
#helmRepositoryOverride: ""
helmRepository: "https://helm-entry" 

# Default secret name for Helm Repo credential. .Value.golbal.helmRepositoryCred will
# override the default value. You can further override uing
#helmRepositoryCredOverride:""
helmRepositoryCred: xapp-mgr-creds

# Default configmap name for Helm Repo cert. .Value.golbal.helmRepositoryCert will
# override the default value. You can further override uing
#helmRepositoryCertOverride:""
helmRepositoryCert: xapp-mgr-certs

# Helm Tiller for xApp
# The global setting will override this default value
# You can further override using helmRepositoryTillerOverride: ""
helmRepositoryTiller: "tiller-deploy" 

# Helm Tiller Namespace for xApp
# The global setting will override this default value
# You can further override using helmRepositoryTillerNamespaceOverride: ""
helmRepositoryTillerNamespace: "kube-system" 


# Helm Tiller port for xApp
# The global setting will override this default value
# You can further override using helmRepositoryTillerPortOverride: ""
helmRepositoryTillerPort: 44134 
# Uncomment the following line to override the docker registry
#repositoryOverride: ""


# Uncomment the following line to override the docker registry credential
#repositoryCredOverride: ""

# Uncomment the following line to override the image pull policy
#imagePullPolicyOverride: ""


appmgr:
  image:
   # xAppmanager Docker image name and tag
   init:
     name: it-dep-init
     tag: latest
   name: ric-plt-appmgr
   tag: 0.1.3

  # This section describes xAppManager
  replicaCount: 1

  reponame: "helm-repo"

  # Service ports are now defined in 
  # ric-common/Common-Template/helm/ric-common/templates/_ports.tpl file.
  # If need to change a service port, make the code change necessary, then
  # update the _ports.tpl file with the new port number.

  # config
  # Path referred in xapp-manager for retrieving configuration details
  appconfigpath: /opt/ric/config


  # secret
  # Path referred in xapp-manager for retrieving helm repo secrets
  appsecretpath: /opt/ric/secret


  # certificates
  # Path referred in xapp-manager for retrieving helm repo client certificates
  appcertpath: /opt/ric/certificates




