################################################################################
#   Copyright (c) 2019 AT&T Intellectual Property.                             #
#   Copyright (c) 2019 Nokia.                                                  #
#                                                                              #
#   Licensed under the Apache License, Version 2.0 (the "License");            #
#   you may not use this file except in compliance with the License.           #
#   You may obtain a copy of the License at                                    #
#                                                                              #
#       http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                              #
#   Unless required by applicable law or agreed to in writing, software        #
#   distributed under the License is distributed on an "AS IS" BASIS,          #
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
#   See the License for the specific language governing permissions and        #
#   limitations under the License.                                             #
################################################################################

kind: "Service"
apiVersion: "v1"
metadata:
  name: {{ include "common.ingressurl.ricplt" . }}
  namespace: {{ include "common.namespace" . }}
spec:
  ports:
    - name: {{ include "common.ingressurl.ricplt" . }}-http-ingress-port
      protocol: "TCP"
      port: 80
    - name: {{ include "common.ingressurl.ricplt" . }}-https-ingress-port
      protocol: "TCP"
      port: 443
---
kind: "Endpoints"
apiVersion: "v1"
metadata:
  # match with the selector-less service
  name: {{ include "common.ingressurl.ricplt" . }}
  namespace: {{ include "common.namespace" . }}
subsets: 
  - addresses:
      - ip: "{{ .Values.ext.ip }}"
    ports:
      - port: {{ include "common.ingresshttpport.ricplt" . }}
        name: {{ include "common.ingressurl.ricplt" . }}-http-ingress-port
      - port: {{ include "common.ingresshttpsport.ricplt" . }}
        name: {{ include "common.ingressurl.ricplt" . }}-https-ingress-port
---
kind: "Service"
apiVersion: "v1"
metadata:
  name: {{ include "common.ingressurl.ricxapp" . }}
  namespace: {{ include "common.namespace" . }}
spec:
  ports:
    - name: {{ include "common.ingressurl.ricxapp" . }}-http-ingress-port
      protocol: "TCP"
      port: 80
    - name: {{ include "common.ingressurl.ricxapp" . }}-https-ingress-port
      protocol: "TCP"
      port: 443
---
kind: "Endpoints"
apiVersion: "v1"
metadata:
  # match with the selector-less service
  name: {{ include "common.ingressurl.ricxapp" . }}
  namespace: {{ include "common.namespace" . }}
subsets: 
  - addresses:
      - ip: "{{ .Values.ext.ip }}"
    ports:
      - port: {{ include "common.ingresshttpport.ricxapp" . }}
        name: {{ include "common.ingressurl.ricxapp" . }}-http-ingress-port
      - port: {{ include "common.ingresshttpsport.ricxapp" . }}
        name: {{ include "common.ingressurl.ricxapp" . }}-https-ingress-port