#  ============LICENSE_START===============================================
#  Copyright (C) 2020-2023 Nordix Foundation. All rights reserved.
#  Copyright (C) 2023-2025 OpenInfra Foundation Europe. All rights reserved.
#  ========================================================================
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#  ============LICENSE_END=================================================
#


apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-producer-pm-xml2json
  labels:
    app: kafka-producer-pm-xml2json

spec:
  replicas: 1
  serviceName: kafka-producer-pm-xml2json
  selector:
    matchLabels:
      app: kafka-producer-pm-xml2json
  template:
    metadata:
      labels:
        app: kafka-producer-pm-xml2json

    spec:
      serviceAccountName: ranpm-component-sa
      initContainers:
      - name: wait-for-keycloak-and-kafka
        securityContext:
          runAsUser: 0
        image: {{ include "repository.nexusProxyRepo" . }}/{{ .Values.global.image.kubectl.name }}:{{ .Values.global.image.kubectl.tag }}
        command: ["/usr/bin/bash"]
        args: ["-c", "cp /opt/app/scripts/init-wait.sh /opt/ && chmod +x /opt/init-wait.sh && /opt/init-wait.sh"]
        volumeMounts:
        - name: kafka-producer-pm-xml2json-cm-config
          mountPath: /opt/app/scripts/init-wait.sh
          subPath: init-wait.sh
      containers:
      - name: kafka-producer-pm-xml2json
        image: {{ include "repository.nexusReleaseRepo" . }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy  }}
        ports:
        - name: http
          containerPort: 80
        env:
        - name: E1
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KP
          valueFrom:
            fieldRef:
              fieldPath: metadata.name

        - name: KAFKA_SERVER
          value: "onap-strimzi-kafka-bootstrap.onap:9095"
        # This property controls the data format used for the conversion
        # Example values:
        #   DATA_TYPE_FORMAT = "" -> older 4G/Default Measurement file format
        #   DATA_TYPE_FORMAT = "TS28532" -> 5G/3GPP-TS-28.532 Measurement file format
        - name: DATA_TYPE_FORMAT
          value: {{ .Values.dataTypeFormat | quote | default "" }}
        - name: ICS
          value: informationservice.nonrtric:9082
        - name: SELF
          value: "$(E1).kafka-producer-pm-xml2json:80"
        - name: FILESTORE_USER
          value: admin
        - name: FILESTORE_PWD
          value: adminadmin
        - name: FILESTORE_SERVER
          value: minio:9000
        - name: CREDS_GRANT_TYPE
          value: client_credentials
        - name: CREDS_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: kafka-pm-xml-2-json
              key: client_secret
        - name: CREDS_CLIENT_ID
          value: kafka-producer-pm-xml2json
        - name: AUTH_SERVICE_URL
          value: http://keycloak.smo:8080/realms/nonrtric-realm/protocol/openid-connect/token
        volumeMounts:
        - mountPath: /application_configuration.json
          subPath: application_configuration.json
          name: kafka-producer-pm-xml2json-cm-config
      volumes:
      - configMap:
          defaultMode: 420
          name: kafka-producer-pm-xml2json-cm-config
        name: kafka-producer-pm-xml2json-cm-config
