################################################################################
#   Copyright (C) 2024-2025 OpenInfra Foundation Europe. All rights reserved.  #
#                                                                              #
#   Licensed under the Apache License, Version 2.0 (the "License");            #
#   you may not use this file except in compliance with the License.           #
#   You may obtain a copy of the License at                                    #
#                                                                              #
#       http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                              #
#   Unless required by applicable law or agreed to in writing, software        #
#   distributed under the License is distributed on an "AS IS" BASIS,          #
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
#   See the License for the specific language governing permissions and        #
#   limitations under the License.                                             #
################################################################################

---

# Preload services for nonrtric install

# https://docs.o-ran-sc.org/projects/o-ran-sc-nonrtric-plt-sme/en/latest/overview.html#

servicemanager:
  AefProfiles:
  - interfaceDescriptions:
    - ipv4Addr: "servicemanager.nonrtric.svc.cluster.local"
      port: 8095
      securityMethods:
      - PKI
    Versions:
      - ApiVersion: "v1"
        Resources:
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          ResourceName: healthcheck
          Uri: "/"
        - CommType: REQUEST_RESPONSE
          Operations:
          - POST
          ResourceName: registrations
          Uri: "/api-provider-management/registrations"
        - CommType: REQUEST_RESPONSE
          Operations:
          - PUT
          - PATCH
          - DELETE
          ResourceName: registrations-domain_id
          Uri: "/api-provider-management/registrations/{registrationId}"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          - POST
          ResourceName: publisher
          Uri: "/published-apis/{apfId}/service-apis"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          - PUT
          - PATCH
          - DELETE
          ResourceName: publisher-api_id
          Uri: "/published-apis/{apfId}/service-apis/{serviceApiId}"
        - CommType: REQUEST_RESPONSE
          Operations:
          - POST
          ResourceName: invoker
          Uri: "/api-invoker-management/onboardedInvokers"
        - CommType: REQUEST_RESPONSE
          Operations:
          - PUT
          - PATCH
          - DELETE
          ResourceName: invoker-invoker_id
          Uri: "/api-invoker-management/onboardedInvokers/{onboardingId}"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          ResourceName: discovery
          Uri: "/service-apis/allServiceAPIs"
  ApiName: servicemanager-http

# https://docs.o-ran-sc.org/projects/o-ran-sc-nonrtric-plt-rappmanager/en/latest/rappmanager-api.html

rappmanager:
  AefProfiles:
  - interfaceDescriptions:
    - ipv4Addr: "rappmanager.nonrtric.svc.cluster.local"
      port: 8080
      securityMethods:
      - PKI
    - ipv4Addr: "rappmanager.nonrtric.svc.cluster.local"
      port: 8433
      securityMethods:
      - PSK
    Versions:
      - ApiVersion: ""
        Resources:
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          - POST
          - PUT
          - DELETE
          ResourceName: "rapps-rappId"
          Uri: "/rapps/{rappId}"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          ResourceName: "rapps"
          Uri: "/rapps"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          - PUT
          - DELETE
          ResourceName: "rapps-instance"
          Uri: "/rapps/{rappId}/instance/{rappInstanceId}"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          - POST
          ResourceName: "rapps-all-instances"
          Uri: "/rapps/{rappId}/instance"
  ApiName: rapp-http

# https://docs.o-ran-sc.org/projects/o-ran-sc-nonrtric-plt-a1policymanagementservice/en/latest/pms-api.html

policymanagementservice:
  AefProfiles:
  - interfaceDescriptions:
    - ipv4Addr: "policymanagementservice.nonrtric.svc.cluster.local"
      port: 8081
      securityMethods:
      - PKI
    - ipv4Addr: "policymanagementservice.nonrtric.svc.cluster.local"
      port: 8433
      securityMethods:
      - PSK
    Versions:
      - ApiVersion: ""
        Resources:
        - CommType: REQUEST_RESPONSE
          Operations:
          - PUT
          ResourceName: "putPolicy"
          Uri: "/a1-policy/v2/policies"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          - DELETE
          ResourceName: "Policy"
          Uri: "/a1-policy/v2/policies/{policy_id}"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          ResourceName: "getPolicyIds"
          Uri: "/a1-policy/v2/policies"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          ResourceName: "getPolicyInstances"
          Uri: "/a1-policy/v2/policy-instances"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          ResourceName: "getPolicyStatus"
          Uri: "/a1-policy/v2/policies/{policy_id}/status"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          ResourceName: "getPolicyTypeDefinition"
          Uri: "/a1-policy/v2/policy-types/{policytype_id}"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          ResourceName: "getPolicyTypes"
          Uri: "/a1-policy/v2/policy-types"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          ResourceName: "health"
          Uri: "/actuator/health"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          ResourceName: "healthPath"
          Uri: "/actuator/health/**"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          ResourceName: "heapdump"
          Uri: "/actuator/heapdump"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          ResourceName: "info"
          Uri: "/actuator/info"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          ResourceName: "ActuatorRootWebEndpoint"
          Uri: "/actuator"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          ResourceName: "logfile"
          Uri: "/actuator/logfile"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          ResourceName: "loggers"
          Uri: "/actuator/loggers"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          - POST
          ResourceName: "loggersName"
          Uri: "/actuator/loggers/{name}"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          ResourceName: "metrics"
          Uri: "/actuator/metrics"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          ResourceName: "metricsRequiredMetricName"
          Uri: "/actuator/metrics/{requiredMetricName}"
        - CommType: REQUEST_RESPONSE
          Operations:
          - POST
          ResourceName: "shutdown"
          Uri: "/actuator/shutdown"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          ResourceName: "threaddump"
          Uri: "/actuator/threaddump"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          - PUT
          ResourceName: "Configuration"
          Uri: "/a1-policy/v2/configuration"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          ResourceName: "getStatus"
          Uri: "/a1-policy/v2/status"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          ResourceName: "getStatusV1"
          Uri: "/status"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          ResourceName: "getRic"
          Uri: "/a1-policy/v2/rics/ric"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          ResourceName: "getRics"
          Uri: "/a1-policy/v2/rics"
        - CommType: REQUEST_RESPONSE
          Operations:
          - DELETE
          ResourceName: "deleteService"
          Uri: "/a1-policy/v2/services/{service_id}"
        - CommType: REQUEST_RESPONSE
          Operations:
          - PUT
          ResourceName: "keepAliveService"
          Uri: "/a1-policy/v2/services/{service_id}/keepalive"
        - CommType: REQUEST_RESPONSE
          Operations:
          - DELETE
          ResourceName: "putService"
          Uri: "/a1-policy/v2/services"
  ApiName: a1-policy-http

# https://docs.o-ran-sc.org/projects/o-ran-sc-nonrtric-plt-informationcoordinatorservice/en/h-release/ics-api.html

informationservice:
  AefProfiles:
  - interfaceDescriptions:
    - ipv4Addr: "informationservice.nonrtric.svc.cluster.local"
      port: 9082
      securityMethods:
      - PKI
    - ipv4Addr: "informationservice.nonrtric.svc.cluster.local"
      port: 9083
      securityMethods:
      - PSK
    Versions:
      - ApiVersion: "v1"
        Resources:
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          ResourceName: "IndividualEIType"
          Uri: "/A1-EI/eitypes/{eiTypeId}"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          ResourceName: "EIJobStatus"
          Uri: "/A1-EI/v1/eijobs/{eiJobId}/status"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          ResourceName: "EITypeIdentifiers"
          Uri: "/A1-EI/eitypes"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          - DELETE
          - PUT
          ResourceName: "IndividualEIJob"
          Uri: "/A1-EI/v1/eijobs/{eiJobId}"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          ResourceName: "EIJobIdentifiers"
          Uri: "/A1-EI/v1/eijobs"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          ResourceName: "ServiceStatus"
          Uri: "/status"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          ResourceName: "threaddump"
          Uri: "/actuator/threaddump"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          ResourceName: "loggers"
          Uri: "/actuator/loggers"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          ResourceName: "health"
          Uri: "/actuator/health"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          ResourceName: "healthPath"
          Uri: "/actuator/health/**"
        - CommType: REQUEST_RESPONSE
          Operations:
          - POST
          ResourceName: "shutdown"
          Uri: "/actuator/shutdown"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          ResourceName: "metrics"
          Uri: "/actuator/metrics"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          ResourceName: "metricsRequiredMetricName"
          Uri: "/actuator/metrics/{requiredMetricName}"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          ResourceName: "ActuatorRootWebEndpoint"
          Uri: "/actuator"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          ResourceName: "info"
          Uri: "/actuator/info"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          ResourceName: "logfile"
          Uri: "/actuator/logfile"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          - POST
          ResourceName: "loggersName"
          Uri: "/actuator/loggers/{name}"
        - CommType: REQUEST_RESPONSE
          Operations:
          - GET
          ResourceName: "heapdump"
          Uri: "/actuator/heapdump"
  ApiName: informationservice-http
