################################################################################
#   Copyright (c) 2019 AT&T Intellectual Property.                             #
#   Copyright (c) 2019 Nokia.                                                  #
#                                                                              #
#   Licensed under the Apache License, Version 2.0 (the "License");            #
#   you may not use this file except in compliance with the License.           #
#   You may obtain a copy of the License at                                    #
#                                                                              #
#       http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                              #
#   Unless required by applicable law or agreed to in writing, software        #
#   distributed under the License is distributed on an "AS IS" BASIS,          #
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
#   See the License for the specific language governing permissions and        #
#   limitations under the License.                                             #
################################################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.deploymentname.dbaas" . }}
  namespace: {{ include "common.namespace.platform" . }}
  labels:
    app: {{ include "common.namespace.platform" . }}-{{ include "common.name.dbaas" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.dbaas.backend.replicas }}
  selector:
    matchLabels:
      app: {{ include "common.namespace.platform" . }}-{{ include "common.name.dbaas" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      {{- if .Values.dbaas.annotations }}
      annotations:
        {{- .Values.dbaas.annotations | nindent 8 -}}
      {{ end }}
      labels:
        app: {{ include "common.namespace.platform" . }}-{{ include "common.name.dbaas" . }}
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
       - name: {{ include "common.repositoryCred" . }}
      terminationGracePeriodSeconds: {{ .Values.dbaas.backend.terminationGracePeriodSeconds }}
      containers:
      - image: {{ include "common.repository" . }}/{{ .Values.dbaas.backend.image.name }}:{{ .Values.dbaas.backend.image.tag }}
        imagePullPolicy: {{ include "common.pullPolicy" . }}
        ports:
        - containerPort: {{ include "common.serviceport.dbaas.tcp" . }}
          name: sql
          protocol: TCP
        name: {{ include "common.containername.dbaas" . }}
      restartPolicy: Always
