# Default values for nexus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# This is the name of K8S secret that contains the docker registry cert
# You can override this by using
# repositoryCertOverride: ""
repositoryCert: docker-reg-certs

# This is designed to be deployed using local image
image:
  repository: nexus-repository-helm-apt
  tag: 1.0.0
  pullPolicy: Never

service:
  port:
    nexus: 80
    docker: 10001
ingress:
  hostpostfix: ricaux.local

